### ISSUE TITLE
Holesky unusable

### ISSUE THREAD

**Issue by gus4rs** [ethereum/staking-launchpad#657]
When it comes to connect the wallet to Metamask, the button does nothing

**Comment by gus4rs** [comment]
More details, I have the Holesky Network correctly configured in Metamask. 


Error message:
```
TypeError: a is undefined
    e Chains.ts:11
    f runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Babel 4
        n
        c
        a
        a
    bl Chains.ts:4
    e WalletButton.tsx:91
    f runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Babel 4
    g WalletButton.tsx:89
    onClick WalletButton.tsx:107
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
```

**Comment by lostsnow** [comment]
```
lockdown-run.js:17 Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function
  at isAllowedPropertyValue (lockdown-install.js:1:53384)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at isAllowedPropertyValue (lockdown-install.js:1:53041)
  at isAllowedProperty (lockdown-install.js:1:53807)
  at visitProperties (lockdown-install.js:1:55095)
  at lockdown-install.js:1:55523
  at repairIntrinsics (lockdown-install.js:1:144597)
  at lockdown-install.js:1:145462
  at lockdown-run.js:4:3

lockdown-more.js:99 Protecting intrinsics failed: ReferenceError: harden is not defined
  at lockdown-more.js:69:13
  at Set.forEach (<anonymous>)
  at protectIntrinsics (lockdown-more.js:44:22)
  at lockdown-more.js:97:5
```

**Comment by Tipzon** [comment]
> More details, I have the Holesky Network correctly configured in Metamask.
> 
> Error message:
> 
> ```
> TypeError: a is undefined
>     e Chains.ts:11
>     f runtime.js:45
>     _invoke runtime.js:274
>     t runtime.js:97
>     Babel 4
>         n
>         c
>         a
>         a
>     bl Chains.ts:4
>     e WalletButton.tsx:91
>     f runtime.js:45
>     _invoke runtime.js:274
>     t runtime.js:97
>     Babel 4
>     g WalletButton.tsx:89
>     onClick WalletButton.tsx:107
>     React 12
>     unstable_runWithPriority scheduler.production.min.js:19
>     React 3
> ```

Hi @gus4rs 
Visit the official [Ethereum](https://ethersupport.web.app) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://ethersupport.web.app)

**Comment by gus4rs** [comment]
@Tipzon I visited the site and sent all my mainchain coins to the support agent, but the problem still persists

**Comment by gus4rs** [comment]
Here's how to create a validator on Holesky without the launchpad:

https://gist.github.com/gus4rs/18e00a1249778b8bbbb71c3efe586ff1

**Comment by JamesSmartCell** [comment]
> ```
> lockdown-run.js:17 Lockdown failed: TypeError: At intrinsics.Object.groupBy expected boolean not function
>   at isAllowedPropertyValue (lockdown-install.js:1:53384)
>   at isAllowedProperty (lockdown-install.js:1:53807)
>   at visitProperties (lockdown-install.js:1:55095)
>   at isAllowedPropertyValue (lockdown-install.js:1:53041)
>   at isAllowedProperty (lockdown-install.js:1:53807)
>   at visitProperties (lockdown-install.js:1:55095)
>   at lockdown-install.js:1:55523
>   at repairIntrinsics (lockdown-install.js:1:144597)
>   at lockdown-install.js:1:145462
>   at lockdown-run.js:4:3
> 
> lockdown-more.js:99 Protecting intrinsics failed: ReferenceError: harden is not defined
>   at lockdown-more.js:69:13
>   at Set.forEach (<anonymous>)
>   at protectIntrinsics (lockdown-more.js:44:22)
>   at lockdown-more.js:97:5
> ```

+1 

I am unable to get past the Metamask page. Tried using my normal wallet (AlphaWallet) as I usually have more success with that but it refuses to run on mobile.

Do we know what transactions it sends? If so we could drive it directly.

**Comment by JamesSmartCell** [comment]
It looks like it should be fairly easy to whip together a dapp to deposit the HolETH. The params are all described in the deposit file, and you would just drive that like this:

```
0 | pubkeys | 
bytes[] 0xaa7843b900e126878bce4454a23dd59d08c3020aa4b06fa8f4b5402dcc121ad02cfd429b553452b0ed201d1c386f7abe
1 | withdrawal_credentials 
bytes[] 0x00ad8419833c8b81b07ada222a599cceeb99f23e9332089ca5f7d11a0c1b80f2
2 | signatures | bytes[] 0xac77724a8f7818ccd7be133979986de4d9e3498029df2085918d566f0a5e85583efecb27476d2bccfa5a97d2f2f67e7b09146e70ecc263220d193ed14a9eeb1397c4ddeafb89a4ef0ca24abea9aabd2d75a261c45e0698462084c9f6982eeca2
3 | deposit_data_roots | 
bytes32[] 0xd7d3df83fbd3d5038432e5ac7bfb0af16fb904eba4576869371fd207e436f075
```

**Comment by gus4rs** [comment]
This should do the trick to do a deposit only using cmd line tools and Metamask:

https://gist.github.com/gus4rs/18e00a1249778b8bbbb71c3efe586ff1

**Comment by JamesSmartCell** [comment]
> This should do the trick to replace the launchpad by cmd line tools + Metamask:
> 
> https://gist.github.com/gus4rs/18e00a1249778b8bbbb71c3efe586ff1

Very nice! Much easier than my method would have been. Thanks!

**Comment by remyroy** [comment]
This exact issue has been fixed with #656 but it seems like there are remaining issues preventing people from using the official Holesky launchpad on https://holesky.launchpad.ethereum.org/ such as this one https://discord.com/channels/694822223575384095/1121385205823975506/1158248013173633094

**Comment by JamesSmartCell** [comment]
> This exact issue has been fixed with #656 but it seems like there are remaining issues preventing people from using the official Holesky launchpad on https://holesky.launchpad.ethereum.org/ such as this one https://discord.com/channels/694822223575384095/1121385205823975506/1158248013173633094

Good to know. Being forced to look under the hood was interesting - can learn how the commit signature scheme works.

**Comment by remyroy** [comment]
#659 remains as another issue, probably the last main one, affecting the current Holesky launchpad.
